services:
  api:
    build: .
    container_name: nest_api
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  worker:
    build: .
    container_name: nest_worker
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    command: node dist/mail/mail.worker.js

  bull-dashboard:
    build: .
    container_name: bull_dashboard
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "3001:3001"
    command: node dist/dashboard/bull-board.js

  postgres:
    image: postgres:15
    container_name: nest_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: nest_redis
    restart: always
    ports:
      - "6379"

volumes:
  postgres_data:
